# Generated by Django 2.2.16 on 2022-02-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220218_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('-pk',)},
        ),
    ]
