# Generated by Django 2.2.16 on 2022-02-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20220220_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-pk',)},
        ),
    ]
