# Generated by Django 2.2.16 on 2022-02-26 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_auto_20220220_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1895, 'Год выпуска не может быть раньше выпуска первого фильма,'), django.core.validators.MaxValueValidator(2100, 'Год выпуска не может быть больше 2100-го года')]),
        ),
    ]
